# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = app/database/migrations

# template used to generate migration file names; The default combo is below.
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s
file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file as well as the filename.
# string_case = utf8

# version path separator; as of Alembic 1.3, this defaults to os.pathsep
# version_path_separator = :

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/urbanair

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
